<?php declare(strict_types = 1);

namespace PhantomanTests\unit;

use Codeception\Extension\Phantoman;
use Codeception\Test\Unit;

class PhantomanTest extends Unit
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAfterSuite(): void
    {

    }

    public function testSuiteInit(): void
    {

    }
}
